SELECT
    a.APNT_NO,
    p.PT_NAME,
    a.PT_NO,
    a.MCDP_CD,
    d.DR_NAME,
    a.APNT_YMD
FROM APPOINTMENT AS a
JOIN DOCTOR As d ON d.DR_ID = a.MDDR_ID
JOIN PATIENT AS p ON p.PT_NO = a.PT_NO
WHERE a.APNT_CNCL_YN = 'N' AND 
      a.MCDP_CD = 'CS' AND
      a.APNT_YMD LIKE "2022-04-13%"
ORDER BY a.APNT_YMD ASC
