SELECT
    DISTINCT h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
JOIN CAR_RENTAL_COMPANY_CAR as c ON c.CAR_ID = h.CAR_ID
WHERE
    CAR_TYPE ="세단" AND 
    MONTH(START_DATE) = 10
ORDER BY c.CAR_ID DESC
