SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    (SUM(o.AMOUNT) * p.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER As o
JOIN FOOD_PRODUCT AS p ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
GROUP BY o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC
