SELECT
    n1.FLAVOR
FROM (SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
    ) AS n1
JOIN (
    SELECT FLAVOR,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
    ) AS n2 ON n1.FLAVOR = n2.FLAVOR
ORDER BY (n2.TOTAL_ORDER + n1.TOTAL_ORDER) DESC
LIMIT 3;
