SELECT
    i.ID,
    n.FISH_NAME,
    r.LENGTH
FROM
    (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) AS r
JOIN FISH_NAME_INFO as n ON n.FISH_TYPE = r.FISH_TYPE
JOIN FISH_INFO as i ON i.LENGTH = r.LENGTH AND i.FISH_TYPE = r.FISH_TYPE
