SELECT
    DISTINCT c.CAR_ID,
    c.CAR_TYPE,
    CASE
        WHEN c.CAR_TYPE = '세단'
        THEN ROUND((c.DAILY_FEE * 30) * 0.92, 0)
        WHEN c.CAR_TYPE = 'SUV'
        THEN ROUND((c.DAILY_FEE * 30) * 0.95, 0)    
    END AS FEE
    
FROM CAR_RENTAL_COMPANY_CAR AS c
WHERE c.CAR_ID NOT IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    ) AND
    c.CAR_TYPE in ('SUV', '세단') AND
    (c.DAILY_FEE * 30) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC
